import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav"; // La barre de navigation de votre site
import styles from "./styles/layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav />
        {children}
        <footer className={styles.footer}>
          <p>
            Porfolio réalisé avec <span>NextJS</span> - © 2025 Yusef Boulam. All
            rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
